CREATE TRIGGER INSERTAR_AGENDADO AFTER INSERT
ON AGENDADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','AGENDADO',CONCAT('ID: ',NEW.ID_AGENDADO,' - , FECHA: ',NEW.FECHA,' - , HORA: ',NEW.HORA,' - , ID_PETICION',NEW.ID_PETICION),NOW());

CREATE TRIGGER ACTUALIZAR_AGENDADO BEFORE UPDATE
ON AGENDADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','AGENDADO',CONCAT('ID: ',NEW.ID_AGENDADO,' - , FECHA: ',NEW.FECHA,' - , HORA: ',NEW.HORA,' - , ID_PETICION',NEW.ID_PETICION),
CONCAT('ID: ',OLD.ID_AGENDADO,' -, FECHA: ',OLD.FECHA,' -, HORA:',OLD.HORA,' -, ID_PETICION:',OLD.PETICION),NOW());

CREATE TRIGGER ELIMINAR_AGENDADO BEFORE DELETE
ON AGENDADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','AGENDADO',CONCAT('ID: ',OLD.ID_AGENDADO,' -, FECHA: ',OLD.FECHA,' -, HORA:',OLD.HORA,' -, ID_PETICION:',OLD.PETICION),'',NOW());

CREATE TRIGGER INSERTAR_ROL AFTER INSERT
ON ROL FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','ROL',CONCAT('ID: ',NEW.ID_ROL ,' -, NOMBRE: ',NEW.NOMBRE),NOW());

CREATE TRIGGER ACTUALIZAR_ROL BEFORE UPDATE
ON ROL FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','ROL',CONCAT('ID: ',OLD.ID_ROL,' -, NOMBRE: ',OLD.NOMBRE),CONCAT('ID: ',NEW.ID_ROL,' -, NOMBRE: ',NEW.NOMBRE),NOW());

CREATE TRIGGER ELIMINAR_ROL BEFORE DELETE
ON ROL FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','ROL',CONCAT('ID: ',OLD.ID_ROL,' -, NOMBRE: ',OLD.NOMBRE),'',NOW());

CREATE TRIGGER INSERTAR_CARACTERISTICA AFTER INSERT
ON CARACTERISTICA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','CARACTERISTICA',CONCAT('ID: ',NEW.ID_CARACTERISTICA,' -, NOMBRE: ',NEW.NOMBRE,' -, ESTADO: ',NEW.ESTADO), NOW());

CREATE TRIGGER ACTUALIZAR_CARACTERISTICA BEFORE UPDATE
ON CARACTERISTICA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','CARACTERISTICAS',CONCAT('ID: ',OLD.ID_CARACTERISTICA,' -, NOMBRE: ',OLD.NOMBRE,' -, ESTADO: ',OLD.ESTADO),
CONCAT('ID: ', NEW.ID_CARACTERISTICA,' -, NOMBRE: ',OLD.NOMBRE,' -, ESTADO: ',OLD.ESTADO),NOW());

CREATE TRIGGER ELIMINAR_CARACTERISTICA BEFORE DELETE
ON CARACTERISTICA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','CARACTERISTICAS',CONCAT('ID: ',OLD.ID_CARACTERISTICA,' -, NOMBRE: ',OLD.NOMBRE,' -, ESTADO: ',OLD.ESTADO),'',NOW());

CREATE TRIGGER INSERTAR_CARACTERISTICASxPETICION AFTER INSERT
ON CARACTERISTICAS_X_PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','CARACTERISTICAS_X_PETICION',CONCAT('ID: ',NEW.ID_CARACTERISTICAS_X_PETICION,' -, VALOR: ', NEW.VALOR,' -, ID_PETICION: ',
NEW.ID_PETICION,' -, ID_CARACTERISTICAS: ',NEW.CARACTERISTICAS),NOW());

CREATE TRIGGER ACTUALIZAR_CARACTERISTICAS_x_PETICION BEFORE UPDATE
ON CARACTERISTICAS_x_PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','CARACTERISTICAS_X_PETICION',CONCAT('ID: ',OLD.ID_CARACTERISTICAS_X_PETICION,' -, VALOR: ', OLD.VALOR,' -, ID_PETICION: ',
OLD.ID_PETICION,' -, ID_CARACTERISTICAS: ',OLD.CARACTERISTICAS),CONCAT('ID: ',NEW.ID_CARACTERISTICAS_X_PETICION,' -, VALOR: ', NEW.VALOR,' -, ID_PETICION: ',
NEW.ID_PETICION,' -, ID_CARACTERISTICAS: ',NEW.CARACTERISTICAS),NOW());

CREATE TRIGGER ELIMINAR_CARACTERISTICAS_x_PETICION BEFORE DELETE
ON CARACTERISTICAS_X_PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','CARACTERISTICAS_X_PETICION',CONCAT('ID: ',OLD.ID_CARACTERISTICAS_X_PETICION,' -, VALOR: ', OLD.VALOR,' -, ID_PETICION: ',
OLD.ID_PETICION,' -, ID_CARACTERISTICAS: ',OLD.CARACTERISTICAS),'',NOW());

CREATE TRIGGER INSERTAR_CARACTERISTICASxSALON AFTER INSERT
ON CARACTERISTICAS_X_SALON FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','CARACTERISTICAS_X_SALON',CONCAT('ID: ',NEW.ID_CARACTERISTICAS_X_SALON,' -, VALOR: ',NEW.VALOR,' -, ID_SALON: ',NEW.ID_SALON,
' -, ID_CARACTERISTICAS: ',NEW.ID_CARACTERISTICAS),NOW());

CREATE TRIGGER ACTUALIZAR_CARACTERISTICASxSALON BEFORE UPDATE
ON CARACTERISTICAS_X_SALON FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','CARACTERISTICAS_X_SALON',CONCAT('ID: ',OLD.ID_CARACTERISTICAS_X_SALON,' -, VALOR: ',OLD.VALOR,' -, ID_SALON: ',OLD.ID_SALON,
' -, ID_CARACTERISTICAS: ',OLD.ID_CARACTERISTICAS),CONCAT('ID: ',NEW.ID_CARACTERISTICAS_X_SALON,' -, VALOR: ',NEW.VALOR,' -, ID_SALON: ',NEW.ID_SALON,
' -, ID_CARACTERISTICAS: ',NEW.ID_CARACTERISTICAS),NOW());

CREATE TRIGGER ELIMINAR_CARACTERISTICASxSALON BEFORE DELETE
ON CARACTERISTICAS_X_SALON FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','CARACTERISTICAS_X_SALON',CONCAT('ID: ',OLD.ID_CARACTERISTICAS_X_SALON,' -, VALOR: ',OLD.VALOR,' -, ID_SALON: ',OLD.ID_SALON,
' -, ID_CARACTERISTICAS: ',OLD.ID_CARACTERISTICAS),'',NOW());

DROP TRIGGER ELIMINAR_ROL;
SELECT * FROM ROL;
SELECT * FROM AUDITORIA;

