CREATE TRIGGER INSERTAR_AGENDADO AFTER INSERT
ON AGENDADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','AGENDADO',CONCAT('ID: ',NEW.ID_AGENDADO,' - , FECHA: ',NEW.FECHA,' - , HORA: ',NEW.HORA,' - , ID_PETICION',NEW.ID_PETICION),NOW());

CREATE TRIGGER INSERTAR_ROL AFTER INSERT
ON ROL FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','ROL',CONCAT('ID: ',NEW.ID_ROL ,' - , NOMBRE: ',NEW.NOMBRE),NOW());

CREATE TRIGGER ACTUALIZAR_ROL BEFORE UPDATE
ON ROL FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','ROL',CONCAT('ID: ',OLD.ID_ROL,' - NOMBRE: ',OLD.NOMBRE),CONCAT('ID: ',NEW.ID_ROL,' - , NOMBRE: ',NEW.NOMBRE),NOW());

CREATE TRIGGER ELIMINAR_ROL BEFORE DELETE
ON ROL FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','ROL',CONCAT('ID: ',OLD.ID_ROL,' - NOMBRE: ',OLD.NOMBRE),'',NOW());

CREATE TRIGGER INSERTAR_CARACTERISTICA AFTER INSERT
ON CARACTERISTICA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','CARACTERISTICA',CONCAT('ID_CARACTERISTICA: ',ID_CARACTERISTICA,' - NOMBRE: ',NOMBRE,' - ESTADO: ',ESTADO), NOW());


DROP TRIGGER ELIMINAR_ROL;
SELECT * FROM ROL;
SELECT * FROM AUDITORIA;

