CREATE TRIGGER INSERTAR_AGENDADO AFTER INSERT
ON AGENDADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','AGENDADO',CONCAT('ID_AGENDADO: ',NEW.ID_AGENDADO,' - , FECHA: ',NEW.FECHA,' - , HORA: ',NEW.HORA,' - , ID_PETICION',NEW.ID_PETICION),NOW());

CREATE TRIGGER ACTUALIZAR_AGENDADO BEFORE UPDATE
ON AGENDADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','AGENDADO',CONCAT('ID_AGENDADO: ',OLD.ID_AGENDADO,' -, FECHA: ',OLD.FECHA,' -, HORA:',OLD.HORA,' -, ID_PETICION:',OLD.ID_PETICION),
CONCAT('ID: ',NEW.ID_AGENDADO,' - , FECHA: ',NEW.FECHA,' - , HORA: ',NEW.HORA,' - , ID_PETICION',NEW.ID_PETICION),NOW());

CREATE TRIGGER ELIMINAR_AGENDADO BEFORE DELETE
ON AGENDADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','AGENDADO',CONCAT('ID_AGENDADO: ',OLD.ID_AGENDADO,' -, FECHA: ',OLD.FECHA,' -, HORA:',OLD.HORA,' -, ID_PETICION:',OLD.ID_PETICION),'',
NOW());

CREATE TRIGGER INSERTAR_CARACTERISTICA AFTER INSERT
ON CARACTERISTICA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','CARACTERISTICA',CONCAT('ID_CARACTERISTICA: ',NEW.ID_CARACTERISTICA,' -, NOMBRE: ',NEW.NOMBRE,' -, ESTADO: ',NEW.ESTADO), NOW());

CREATE TRIGGER ACTUALIZAR_CARACTERISTICA BEFORE UPDATE
ON CARACTERISTICA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','CARACTERISTICAS',CONCAT('ID_CARACTERISTICA: ',OLD.ID_CARACTERISTICA,' -, NOMBRE: ',OLD.NOMBRE,' -, ESTADO: ',OLD.ESTADO),
CONCAT('ID: ', NEW.ID_CARACTERISTICA,' -, NOMBRE: ',OLD.NOMBRE,' -, ESTADO: ',OLD.ESTADO),NOW());

CREATE TRIGGER ELIMINAR_CARACTERISTICA BEFORE DELETE
ON CARACTERISTICA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','CARACTERISTICAS',CONCAT('ID_CARACTERISTICA: ',OLD.ID_CARACTERISTICA,' -, NOMBRE: ',OLD.NOMBRE,' -, ESTADO: ',OLD.ESTADO),'',NOW());

CREATE TRIGGER INSERTAR_CARACTERISTICASxPETICION AFTER INSERT
ON CARACTERISTICAS_X_PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','CARACTERISTICAS_X_PETICION',CONCAT('ID_CARACTERISTICAS_X_PETICION: ',NEW.ID_CARACTERISTICAS_X_PETICION,' -, VALOR: ', NEW.VALOR,' -, ID_PETICION: ',
NEW.ID_PETICION,' -, ID_CARACTERISTICAS: ',NEW.ID_CARACTERISTICAS),NOW());

CREATE TRIGGER ACTUALIZAR_CARACTERISTICAS_x_PETICION BEFORE UPDATE
ON CARACTERISTICAS_x_PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','CARACTERISTICAS_X_PETICION',CONCAT('ID_CARACTERISTICAS_X_PETICION: ',OLD.ID_CARACTERISTICAS_X_PETICION,' -, VALOR: ', OLD.VALOR,' -, ID_PETICION: ',
OLD.ID_PETICION,' -, ID_CARACTERISTICAS: ',OLD.ID_CARACTERISTICAS),CONCAT('ID: ',NEW.ID_CARACTERISTICAS_X_PETICION,' -, VALOR: ', NEW.VALOR,' -, ID_PETICION: ',
NEW.ID_PETICION,' -, ID_CARACTERISTICAS: ',NEW.ID_CARACTERISTICAS),NOW());

CREATE TRIGGER ELIMINAR_CARACTERISTICAS_x_PETICION BEFORE DELETE
ON CARACTERISTICAS_X_PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','CARACTERISTICAS_X_PETICION',CONCAT('ID_CARACTERISTICAS_X_PETICION: ',OLD.ID_CARACTERISTICAS_X_PETICION,' -, VALOR: ', OLD.VALOR,' -, ID_PETICION: ',
OLD.ID_PETICION,' -, ID_CARACTERISTICAS: ',OLD.ID_CARACTERISTICAS),'',NOW());

CREATE TRIGGER INSERTAR_CARACTERISTICASxSALON AFTER INSERT
ON CARACTERISTICAS_X_SALON FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','CARACTERISTICAS_X_SALON',CONCAT('ID_CARACTERISTICAS_X_SALON: ',NEW.ID_CARACTERISTICAS_X_SALON,' -, VALOR: ',NEW.VALOR,' -, ID_SALON: ',NEW.ID_SALON,
' -, ID_CARACTERISTICAS: ',NEW.ID_CARACTERISTICAS),NOW());

CREATE TRIGGER ACTUALIZAR_CARACTERISTICASxSALON BEFORE UPDATE
ON CARACTERISTICAS_X_SALON FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','CARACTERISTICAS_X_SALON',CONCAT('ID_CARACTERISTICAS_X_SALON: ',OLD.ID_CARACTERISTICAS_X_SALON,' -, VALOR: ',OLD.VALOR,' -, ID_SALON: ',OLD.ID_SALON,
' -, ID_CARACTERISTICAS: ',OLD.ID_CARACTERISTICAS),CONCAT('ID_CARACTERISTICAS_X_SALON: ',NEW.ID_CARACTERISTICAS_X_SALON,' -, VALOR: ',NEW.VALOR,' -, ID_SALON: ',NEW.ID_SALON,
' -, ID_CARACTERISTICAS: ',NEW.ID_CARACTERISTICAS),NOW());

CREATE TRIGGER ELIMINAR_CARACTERISTICASxSALON BEFORE DELETE
ON CARACTERISTICAS_X_SALON FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','CARACTERISTICAS_X_SALON',CONCAT('ID_CARACTERISTICAS_X_SALON: ',OLD.ID_CARACTERISTICAS_X_SALON,' -, VALOR: ',OLD.VALOR,' -, ID_SALON: ',OLD.ID_SALON,
' -, ID_CARACTERISTICAS: ',OLD.ID_CARACTERISTICAS),'',NOW());

CREATE TRIGGER INSERTAR_ESTADO AFTER INSERT
ON ESTADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','ESTADO',CONCAT('ID_ESTADO: ',NEW.ID_ESTADO,' -, DESCRIPCION: ',NEW.DESCRIPCION),NOW());

CREATE TRIGGER ACTUALIZAR_ESTADO BEFORE UPDATE
ON ESTADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','ESTADO',CONCAT('ID_ESTADO: ',OLD.ID_ESTADO,' -, DESCRIPCION: ',OLD.DESCRIPCION),CONCAT('ID: ',NEW.ID_ESTADO,' -, DESCRIPCION: ',
NEW.DESCRIPCION),NOW());

CREATE TRIGGER ELIMINAR_ESTADO BEFORE DELETE
ON ESTADO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','ESTADO',CONCAT('ID_ESTADO: ',OLD.ID_ESTADO,' -, DESCRIPCION: ',OLD.DESCRIPCION),'',NOW());

CREATE TRIGGER INSERTAR_IMPLEMENTO AFTER INSERT
ON IMPLEMENTO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','IMPLEMENTO',CONCAT('ID_IMPLEMENTO: ',NEW.ID_IMPLEMENTO,' -, NOMBRE: ',NEW.NOMBRE,' -, CANTIDAD: ',NEW.CANTIDAD,' -, ACTIVO: ',NEW.ACTIVO),NOW());

CREATE TRIGGER ACTUALIZAR_IMPLEMENTO BEFORE UPDATE
ON IMPLEMENTO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','IMPLEMENTO',CONCAT('ID_IMPLEMENTO: ',OLD.ID_IMPLEMENTO,' -, NOMBRE: ',OLD.NOMBRE,' -, CANTIDAD: ',OLD.CANTIDAD,' -, ACTIVO: ',OLD.ACTIVO),
CONCAT('ID_IMPLEMENTO: ',NEW.ID_IMPLEMENTO,' -, NOMBRE: ',NEW.NOMBRE,' -, CANTIDAD: ',NEW.CANTIDAD,' -, ACTIVO: ',NEW.ACTIVO),NOW());

CREATE TRIGGER ELIMINAR_IMPLEMENTO BEFORE DELETE
ON IMPLEMENTO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','IMPLEMENTO',CONCAT('ID_IMPLEMENTO: ',OLD.ID_IMPLEMENTO,' -, NOMBRE: ',OLD.NOMBRE,' -, CANTIDAD: ',OLD.CANTIDAD,' -, ACTIVO: ',OLD.ACTIVO),
'',NOW());

CREATE TRIGGER INSERTAR_IMPLEMENTOSxPETICION AFTER INSERT
ON IMPLEMENTOS_X_PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','IMPLEMENTO_X_PETICION',CONCAT('ID_IMPLEMENTO_X_PETICION: ',NEW.ID_IMPLEMENTOS_X_PETICION,' -, CANTIDAD: ',NEW.CANTIDAD,
' -, ID_IMPLEMENTO:',NEW.ID_IMPLEMENTO,' -, ID_PETICION: ',NEW.ID_PETICION),NOW());

CREATE TRIGGER ACTUALIZAR_IMPLEMENTOSxPETICION BEFORE UPDATE
ON IMPLEMENTOS_X_PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','IMPLEMENTO_X_PETICION',CONCAT('ID_IMPLEMENTO_X_PETICION: ',OLD.ID_IMPLEMENTOS_X_PETICION,' -, CANTIDAD: ',OLD.CANTIDAD,
' -, ID_IMPLEMENTO:',OLD.ID_IMPLEMENTO,' -, ID_PETICION: ',OLD.ID_PETICION),CONCAT('ID_IMPLEMENTO_X_PETICION: ',NEW.ID_IMPLEMENTOS_X_PETICION,
' -, CANTIDAD: ',NEW.CANTIDAD,' -, ID_IMPLEMENTO:',NEW.ID_IMPLEMENTO,' -, ID_PETICION: ',NEW.ID_PETICION),NOW());

CREATE TRIGGER ELIMINAR_IMPLEMENTOSxPETICION BEFORE DELETE
ON IMPLEMENTOS_X_PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','IMPLEMENTO_X_PETICION',CONCAT('ID_IMPLEMENTO_X_PETICION: ',OLD.ID_IMPLEMENTOS_X_PETICION,' -, CANTIDAD: ',OLD.CANTIDAD,
' -, ID_IMPLEMENTO:',OLD.ID_IMPLEMENTO,' -, ID_PETICION: ',OLD.ID_PETICION),'',NOW());

CREATE TRIGGER INSERTAR_PETICION AFTER INSERT
ON PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','PETICION',CONCAT('ID_PETICION: ',NEW.ID_PETICION,' -, FECHA_INICION: ',NEW.FECHA_INICIO,' -, FECHA_FINAL:',NEW.FECHA_FINAL,
' -, OBSERVACION: ',NEW.OBSERVACION,' -, ID_ESTADO: ',NEW.ID_ESTADO,' -, ID_SALON: ',ID_SALON,' -, ID_USUARIO: ',NEW.ID_USUARIO),NOW());

CREATE TRIGGER ACTUALIZAR_PETICION BEFORE UPDATE
ON PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','PETICION',CONCAT('ID_PETICION: ',OLD.ID_PETICION,' -, FECHA_INICION: ',OLD.FECHA_INICIO,' -, FECHA_FINAL:',OLD.FECHA_FINAL,
' -, OBSERVACION: ',OLD.OBSERVACION,' -, ID_ESTADO: ',OLD.ID_ESTADO,' -, ID_SALON: ',OLD.ID_SALON,' -, ID_USUARIO: ',OLD.ID_USUARIO),
CONCAT('ID_PETICION: ',NEW.ID_PETICION,' -, FECHA_INICION: ',NEW.FECHA_INICIO,' -, FECHA_FINAL:',NEW.FECHA_FINAL,
' -, OBSERVACION: ',NEW.OBSERVACION,' -, ID_ESTADO: ',NEW.ID_ESTADO,' -, ID_SALON: ',NEW.ID_SALON,' -, ID_USUARIO: ',NEW.ID_USUARIO),NOW());

CREATE TRIGGER ELIMINAR_PETICION BEFORE DELETE
ON PETICION FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','PETICION',CONCAT('ID_PETICION: ',OLD.ID_PETICION,' -, FECHA_INICION: ',OLD.FECHA_INICIO,' -, FECHA_FINAL:',OLD.FECHA_FINAL,
' -, OBSERVACION: ',OLD.OBSERVACION,' -, ID_ESTADO: ',OLD.ID_ESTADO,' -, ID_SALON: ',OLD.ID_SALON,' -, ID_USUARIO: ',OLD.ID_USUARIO),'',NOW());

CREATE TRIGGER INSERTAR_PROGRAMA AFTER INSERT
ON PROGRAMA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'INSERT','PROGRAMA',CONCAT('ID_PROGRAMA: ',NEW.ID_PROGRAMA,' -, NOMBRE: ',NEW.NOMBRE,' -, FACULTAD:',NEW.FACULTAD,
' -, CODIGO: ',NEW.CODIGO),NOW());

CREATE TRIGGER ACTUALIZAR_PROGRAMA BEFORE UPDATE
ON PROGRAMA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','PROGRAMA',CONCAT('ID_PROGRAMA: ',OLD.ID_PROGRAMA,' -, NOMBRE: ',OLD.NOMBRE,' -, FACULTAD:',OLD.FACULTAD,
' -, CODIGO: ',OLD.CODIGO),CONCAT('ID_PROGRAMA: ',NEW.ID_PROGRAMA,' -, NOMBRE: ',NEW.NOMBRE,' -, FACULTAD:',NEW.FACULTAD,
' -, CODIGO: ',NEW.CODIGO),NOW());

CREATE TRIGGER ELIMINAR_PROGRAMA BEFORE DELETE
ON PROGRAMA FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','PROGRAMA',CONCAT('ID_PROGRAMA: ',OLD.ID_PROGRAMA,' -, NOMBRE: ',OLD.NOMBRE,' -, FACULTAD:',OLD.FACULTAD,
' -, CODIGO: ',OLD.CODIGO),'',NOW());

CREATE TRIGGER INSERTAR_ROL AFTER INSERT
ON ROL FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','ROL',CONCAT('ID_ROL: ',NEW.ID_ROL ,' -, NOMBRE: ',NEW.NOMBRE),NOW());

CREATE TRIGGER ACTUALIZAR_ROL BEFORE UPDATE
ON ROL FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'UPDATE','ROL',CONCAT('ID_ROL: ',OLD.ID_ROL,' -, NOMBRE: ',OLD.NOMBRE),CONCAT('ID: ',NEW.ID_ROL,' -, NOMBRE: ',NEW.NOMBRE),NOW());

CREATE TRIGGER ELIMINAR_ROL BEFORE DELETE
ON ROL FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES(USER(),'DELETE','ROL',CONCAT('ID_ROL: ',OLD.ID_ROL,' -, NOMBRE: ',OLD.NOMBRE),'',NOW());

CREATE TRIGGER INSERTAR_SALON AFTER INSERT
ON SALON FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','SALON',CONCAT('ID_SALON: ',NEW.ID_SALON ,' -, CODIGO: ',NEW.CODIGO,' -, ESTADO: ',NEW.ESTADO,' -, BLOQUE: ',NEW.BLOQUE,
' -, TIPO: ',NEW.TIPO,' -, DESCRIPCION: ',NEW.DESCRIPCION),NOW());

CREATE TRIGGER ACTUALIZAR_SALON BEFORE UPDATE
ON SALON FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'UPDATE','SALON',CONCAT('ID_SALON: ',OLD.ID_SALON ,' -, CODIGO: ',OLD.CODIGO,' -, ESTADO: ',OLD.ESTADO,' -, BLOQUE: ',OLD.BLOQUE,
' -, TIPO: ',OLD.TIPO,' -, DESCRIPCION: ',OLD.DESCRIPCION),CONCAT('ID_SALON: ',NEW.ID_SALON ,' -, CODIGO: ',NEW.CODIGO,' -, ESTADO: ',NEW.ESTADO,' -, BLOQUE: ',NEW.BLOQUE,
' -, TIPO: ',NEW.TIPO,' -, DESCRIPCION: ',NEW.DESCRIPCION),NOW());

CREATE TRIGGER ELIMINAR_SALON BEFORE DELETE
ON SALON FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'DELETE','SALON',CONCAT('ID_SALON: ',OLD.ID_SALON ,' -, CODIGO: ',OLD.CODIGO,' -, ESTADO: ',OLD.ESTADO,' -, BLOQUE: ',OLD.BLOQUE,
' -, TIPO: ',OLD.TIPO,' -, DESCRIPCION: ',OLD.DESCRIPCION),'',NOW());

CREATE TRIGGER INSERTAR_USUARIO AFTER INSERT
ON USUARIO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'INSERT','USUARIO',CONCAT('ID_USUARIO: ',NEW.ID_USUARIO ,' -, PRIMER_NOMBRE: ',NEW.PRIMER_NOMBRE,' -, SEGUNDO_NOMBRE: ',
NEW.SEGUNDO_NOMBRE,' -, PRIMER_APELLIDO: ',NEW.PRIMER_APELLIDO,' -, SEGUNDO_APELLIDO: ',NEW.SEGUNDO_APELLIDO,' -, CORREO: ',NEW.CORREO,' -, CODIGO: ',
NEW.CODIGO,' -, NRO_IDENTIFICACION: ',NEW.NRO_IDENTIFICACION,' -, TELEFONO: ',NEW.TELEFONO,' -, PASSWORD: ',NEW.PASSWORD,' -, CAMBIO_PASSWORD: ',
NEW.CAMBIO_PASSWORD,' -, ESTADO: ',NEW.ESTADO,' -, ID_ROL: ',NEW.ID_ROL,' -, ID_PROGRAMA: ',NEW.ID_PROGRAMA),NOW());

CREATE TRIGGER ACTUALIZAR_USUARIO BEFORE UPDATE
ON USUARIO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'UPDATE','USUARIO',CONCAT('ID_USUARIO: ',OLD.ID_USUARIO ,' -, PRIMER_NOMBRE: ',OLD.PRIMER_NOMBRE,' -, SEGUNDO_NOMBRE: ',
OLD.SEGUNDO_NOMBRE,' -, PRIMER_APELLIDO: ',OLD.PRIMER_APELLIDO,' -, SEGUNDO_APELLIDO: ',OLD.SEGUNDO_APELLIDO,' -, CORREO: ',OLD.CORREO,' -, CODIGO: ',
OLD.CODIGO,' -, NRO_IDENTIFICACION: ',OLD.NRO_IDENTIFICACION,' -, TELEFONO: ',OLD.TELEFONO,' -, PASSWORD: ',OLD.PASSWORD,' -, CAMBIO_PASSWORD: ',
OLD.CAMBIO_PASSWORD,' -, ESTADO: ',OLD.ESTADO,' -, ID_ROL: ',OLD.ID_ROL,' -, ID_PROGRAMA: ',OLD.ID_PROGRAMA),CONCAT('ID_USUARIO: ',NEW.ID_USUARIO ,' -, PRIMER_NOMBRE: ',NEW.PRIMER_NOMBRE,' -, SEGUNDO_NOMBRE: ',
NEW.SEGUNDO_NOMBRE,' -, PRIMER_APELLIDO: ',NEW.PRIMER_APELLIDO,' -, SEGUNDO_APELLIDO: ',NEW.SEGUNDO_APELLIDO,' -, CORREO: ',NEW.CORREO,' -, CODIGO: ',
NEW.CODIGO,' -, NRO_IDENTIFICACION: ',NEW.NRO_IDENTIFICACION,' -, TELEFONO: ',NEW.TELEFONO,' -, PASSWORD: ',NEW.PASSWORD,' -, CAMBIO_PASSWORD: ',
NEW.CAMBIO_PASSWORD,' -, ESTADO: ',NEW.ESTADO,' -, ID_ROL: ',NEW.ID_ROL,' -, ID_PROGRAMA: ',NEW.ID_PROGRAMA),NOW());

CREATE TRIGGER ELIMINAR_USUARIO BEFORE DELETE
ON USUARIO FOR EACH ROW
INSERT INTO auditoria(ID_USUARIO,ACCION,TABLA,ANTIGUO_VALOR,NUEVO_VALOR,FECHA_MODIFICACION)
VALUES (USER(),'DELETE','USUARIO',CONCAT('ID_USUARIO: ',OLD.ID_USUARIO ,' -, PRIMER_NOMBRE: ',OLD.PRIMER_NOMBRE,' -, SEGUNDO_NOMBRE: ',
OLD.SEGUNDO_NOMBRE,' -, PRIMER_APELLIDO: ',OLD.PRIMER_APELLIDO,' -, SEGUNDO_APELLIDO: ',OLD.SEGUNDO_APELLIDO,' -, CORREO: ',OLD.CORREO,' -, CODIGO: ',
OLD.CODIGO,' -, NRO_IDENTIFICACION: ',OLD.NRO_IDENTIFICACION,' -, TELEFONO: ',OLD.TELEFONO,' -, PASSWORD: ',OLD.PASSWORD,' -, CAMBIO_PASSWORD: ',
OLD.CAMBIO_PASSWORD,' -, ESTADO: ',OLD.ESTADO,' -, ID_ROL: ',OLD.ID_ROL,' -, ID_PROGRAMA: ',OLD.ID_PROGRAMA),'',NOW());



