#Base de datos
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/asignacion_salon
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

#Log
logging:
  file: C:/asignacion_salones/asignacion_salon.log