server: 
  port: 8083
#Base de datos
spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/asignacion_salon?useSSL=false
    username: root
    password: 123456
    initialization-mode: always
  mail:
    host: smtp.gmail.com
    port: 587 
    username: rcastellanos1026@gmail.com 
    password: 1102361630
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: false

#Log
logging:
  file: C:/asignacion_salones/asignacion_salon.log
  
  