server: 
  port: 8082
#Base de datos
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/asignacion_salon
    username: root
    password: 123456
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587 
    username: rcastellanos1026@gmail.com 
    password: 1102361630
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    cache: false

#Log
logging:
  file: C:/asignacion_salones/asignacion_salon.log